/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'Spring Framework',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Spring Framework',
        description: 'Comprehensive guides for Spring Boot, Data JPA, Transactions, AOP, and more.',
        slug: '/category/spring-framework',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'spring',
        },
      ],
    },
    {
      type: 'category',
      label: 'React',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'react',
        },
      ],
    },
    {
      type: 'category',
      label: 'Go',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'go',
        },
      ],
    },
    {
      type: 'category',
      label: 'Miscellaneous',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'miscellaneous',
        },
      ],
    },
  ],
};

export default sidebars;
