name: Check Preview
permissions:
  id-token: write
  contents: write
  pull-requests: write

on:
  pull_request: 
    types: [opened, synchronize, reopened, closed, converted_to_draft]
jobs:
  Preview:
    if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth : 0

      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Determin PR_NUMBER and BASE_URL
        id: pr_info
        run: |
          PR_NUMBER="${{github.event.pull_request.number}}"
          BASE_URL="/deploy_preview/release/pr-${PR_NUMBER}/"
          ESCAPED_BASE_URL="\/deploy_preview\/release\/pr-${PR_NUMBER}\/"
          echo $PR_NUMBER
          echo $BASE_URL
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "BASE_URL=$BASE_URL" >> $GITHUB_OUTPUT
          echo "ESCAPED_BASE_URL=$ESCAPED_BASE_URL" >> $GITHUB_OUTPUT
      
      - name: Build Project
        run : |
            PR_NUMBER="${{ steps.pr_info.outputs.PR_NUMBER }}"
            BASE_URL="${{ steps.pr_info.outputs.BASE_URL }}"
            ESCAPED_BASE_URL="${{ steps.pr_info.outputs.ESCAPED_BASE_URL }}"
            # sed -i "s|baseUrl: (.*?),/baseUrl: '${BASE_URL}',/g" docusaurus.config.js
            # change the base URL in docusaurus.config.js
            sed -i "s/baseUrl: '[^']*'/baseUrl: '$ESCAPED_BASE_URL'/" docusaurus.config.js
            echo "BASE_URL=$BASE_URL"
            cat docusaurus.config.js
      
      - name: add a PR comment in a table format
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            | Name | Link |
            |---|---|
            | 😎 Deploy Preview | <https://staging.docs.digital.ai${{ steps.pr_info.outputs.BASE_URL }}> |
            | 📱 Preview On Mobile | ![QR Code](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https://staging.docs.digital.ai${{ steps.pr_info.outputs.BASE_URL }}&color=498500&ecc=Q) |


  cleanup-pr:
    if: github.event.action == 'closed' || github.event.action == 'converted_to_draft' || github.event.action == 'merged'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth : 0

      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Determin PR_NUMBER and BASE_URL
        id: pr_info
        run: |
          PR_NUMBER="${{github.event.pull_request.number}}"
          BASE_URL="/deploy_preview/release/pr-${PR_NUMBER}"
          ESCAPED_BASE_URL="\/deploy_preview\/release\/pr-${PR_NUMBER}"
          echo $PR_NUMBER
          echo $BASE_URL
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "BASE_URL=$BASE_URL" >> $GITHUB_OUTPUT
          echo "ESCAPED_BASE_URL=$ESCAPED_BASE_URL" >> $GITHUB_OUTPUT
      
      - name: add a PR comment in a table format
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            "Removing Deploy Preview from staging on url https://staging.docs.digital.ai${{ steps.pr_info.outputs.BASE_URL }}"

      - name: Remove Deploy preview from staging
        run: |
          echo "Removing Deploy Preview from staging on url https://staging.docs.digital.ai${{ steps.pr_info.outputs.BASE_URL }}"
